server:
  port: 0
spring:
  application:
    name: users-ws
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8700/eureka

management:
  endpoints:
    web:
      exposure:
        include:
          - health

#sample:
#  message: "Hello From Users service"